"""9x9 cross-agent reward correlation matrix + clustering.

Deferred item 5 of the v0 plan. Computes Pearson correlation between every
pair of reward computers, scored on the *same* trajectories. Two regimes:

- ``random``  — episodes generated by uniform-random actions (a uniform
                exploration prior). Establishes the "before training" baseline.
- ``trained`` — episodes generated by each trained policy. Aggregated across
                all 9 agents x 5 seeds, gives the post-training correlation.

The "n agents wearing 3-4 costumes" prediction is tested by clustering the
correlation matrix. Implementation: hierarchical clustering on the
distance matrix d = 1 - |rho|, with a fixed threshold; report cluster count.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np

from traits_audit.committee.rewards import REWARD_REGISTRY
from traits_audit.committee.analysis.rollouts import (
    RolloutTrace,
    random_policy,
    run_rollout,
    sac_policy,
    score_trace,
)


AGENT_NAMES: list[str] = list(REWARD_REGISTRY.keys())


@dataclass
class CorrelationResult:
    """Output of one correlation regime.

    Attributes
    ----------
    matrix : np.ndarray, shape (9, 9)
        Pearson correlation, agent_i vs agent_j, computed over all
        per-step rewards pooled across all source trajectories.
    n_episodes : int
        How many episodes contributed to the pool.
    n_samples_per_episode : int
        Steps per episode (after warm-start).
    agent_names : list[str]
        Row/column order. Same as REWARD_REGISTRY keys.
    """

    matrix: np.ndarray
    n_episodes: int
    n_samples_per_episode: int
    agent_names: list[str]


def _pool_scores(traces: list[RolloutTrace]) -> dict[str, np.ndarray]:
    """Score every trace with every reward computer, concatenated."""
    per_agent: dict[str, list[np.ndarray]] = {n: [] for n in AGENT_NAMES}
    for tr in traces:
        scored = score_trace(tr)
        for n in AGENT_NAMES:
            per_agent[n].append(scored[n])
    return {n: np.concatenate(per_agent[n]) for n in AGENT_NAMES}


def _correlation_matrix(scores: dict[str, np.ndarray]) -> np.ndarray:
    stacked = np.stack([scores[n] for n in AGENT_NAMES], axis=0)
    # np.corrcoef returns NaN if a row has zero variance. Replace with 0
    # so the heatmap renders and clustering treats it as "uncorrelated".
    with np.errstate(invalid="ignore", divide="ignore"):
        m = np.corrcoef(stacked)
    return np.nan_to_num(m, nan=0.0)


def random_rollout_correlation(
    n_episodes: int = 50,
    episode_length: int = 100,
    seed: int = 0,
) -> CorrelationResult:
    """Cross-agent reward correlation under uniform-random acquisition."""
    rng = np.random.default_rng(seed)
    traces: list[RolloutTrace] = []
    for ep in range(n_episodes):
        ep_seed = int(rng.integers(0, 2**31 - 1))
        ep_rng = np.random.default_rng(ep_seed + 1)
        traces.append(run_rollout(
            policy=random_policy(ep_rng),
            seed=ep_seed,
            episode_length=episode_length,
        ))
    scores = _pool_scores(traces)
    mat = _correlation_matrix(scores)
    return CorrelationResult(
        matrix=mat,
        n_episodes=n_episodes,
        n_samples_per_episode=episode_length,
        agent_names=list(AGENT_NAMES),
    )


def trained_policy_correlation(
    models_dir: Path,
    seeds: list[int],
    n_episodes_per_seed: int = 50,
    episode_length: int = 100,
    rng_seed: int = 0,
) -> CorrelationResult:
    """Cross-agent reward correlation under each agent's trained policy.

    For each (agent, training_seed), loads the model and rolls out
    ``n_episodes_per_seed`` deployment episodes. All trajectories from all
    (agent, seed) combinations are pooled before computing the 9x9 matrix.

    This is the "after training" version of the matrix. The clustering on
    this matrix is what the v0 plan calls "the 9-wearing-3-4 result".
    """
    from stable_baselines3 import SAC

    rng = np.random.default_rng(rng_seed)
    traces: list[RolloutTrace] = []
    for agent_name in AGENT_NAMES:
        for s in seeds:
            model_path = models_dir / f"{agent_name}_seed{s}.zip"
            if not model_path.exists():
                raise FileNotFoundError(f"Missing trained model: {model_path}")
            model = SAC.load(str(model_path))
            for _ in range(n_episodes_per_seed):
                ep_seed = int(rng.integers(0, 2**31 - 1))
                traces.append(run_rollout(
                    policy=sac_policy(model),
                    seed=ep_seed,
                    episode_length=episode_length,
                ))

    scores = _pool_scores(traces)
    mat = _correlation_matrix(scores)
    return CorrelationResult(
        matrix=mat,
        n_episodes=len(traces),
        n_samples_per_episode=episode_length,
        agent_names=list(AGENT_NAMES),
    )


# -- Clustering ------------------------------------------------------------

def cluster_agents(
    matrix: np.ndarray,
    threshold: float = 0.5,
) -> tuple[np.ndarray, int]:
    """Hierarchical clustering on d = 1 - |rho| with average linkage.

    Returns
    -------
    labels : np.ndarray, shape (9,)
        Cluster id per agent, in REWARD_REGISTRY order.
    n_clusters : int
        Distinct cluster count.

    The v0 prediction is n_clusters in [3, 4] on the trained matrix. The
    threshold is on cophenetic distance: at threshold=0.5 a pair must have
    |rho| >= 0.5 to share a cluster (at average linkage). Tune by inspecting
    the dendrogram if needed.
    """
    from scipy.cluster.hierarchy import fcluster, linkage
    from scipy.spatial.distance import squareform

    dist = 1.0 - np.abs(matrix)
    # Force the diagonal to exactly 0 — float roundoff in 1 - |rho| can
    # leave -1e-17, which squareform rejects.
    np.fill_diagonal(dist, 0.0)
    condensed = squareform(dist, checks=False)
    Z = linkage(condensed, method="average")
    labels = fcluster(Z, t=threshold, criterion="distance")
    return labels, int(len(np.unique(labels)))


# -- Rendering -------------------------------------------------------------

def render_heatmap(
    result: CorrelationResult,
    title: str,
    output_path: Path,
    cluster_labels: Optional[np.ndarray] = None,
) -> None:
    """Save a labelled heatmap. If cluster_labels provided, reorder by cluster."""
    import matplotlib.pyplot as plt

    names = result.agent_names
    mat = result.matrix
    if cluster_labels is not None:
        order = np.argsort(cluster_labels, kind="stable")
        mat = mat[order][:, order]
        names = [names[i] for i in order]

    fig, ax = plt.subplots(figsize=(8.5, 7))
    im = ax.imshow(mat, cmap="RdBu_r", vmin=-1.0, vmax=1.0, aspect="equal")
    ax.set_xticks(range(len(names)))
    ax.set_yticks(range(len(names)))
    ax.set_xticklabels(names, rotation=45, ha="right")
    ax.set_yticklabels(names)
    for i in range(len(names)):
        for j in range(len(names)):
            ax.text(j, i, f"{mat[i, j]:+.2f}",
                    ha="center", va="center",
                    color="white" if abs(mat[i, j]) > 0.5 else "black",
                    fontsize=7)
    ax.set_title(title)
    fig.colorbar(im, ax=ax, shrink=0.8, label="Pearson correlation")
    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=140)
    plt.close(fig)


def write_csv(result: CorrelationResult, output_path: Path) -> None:
    """Dump the matrix as CSV with row/column names."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    header = "agent," + ",".join(result.agent_names)
    rows = [header]
    for i, name in enumerate(result.agent_names):
        rows.append(name + "," + ",".join(f"{v:.6f}" for v in result.matrix[i]))
    output_path.write_text("\n".join(rows) + "\n")
